server:
  port: ${SERVER_PORT:8080}
  tomcat:
    threads:
      max: 6
spring:
  jpa:
    hibernate.ddl-auto: validate
  output.ansi.enabled: always
  jmx.enabled: false
#  main:
#    allow-circular-references: true

  threads:
    virtual:
      enabled: false