version: '3'

#silent: true

vars:
  APP: '~/tmp'
  CONNECTIONS: 128
  THREADS: 4
  DURATION: 40s
#  URL: 'http://localhost:8080/api/v1/books/random/limit/5'
  URL: 'http://localhost:8080/api/v1/books/random/rows/1000/limit/5/cached'
  RATE: 2500
  SEQ: '5000-25100,{{.RATE}}'
  R_MASK: '{{"{{R}}"}}'

tasks:
  shot:
    desc: 'wrkx - one shot'
    cmds:
      - ~/work/devhands.io/wrk -c{{.CONNECTIONS}} -t{{.THREADS}} -R{{.RATE}} -d{{.DURATION}} -L {{.URL}}

  blast:
    desc: 'wrkx - shot  sequence'
    dir: '{{.APP}}'
    cmds:
      - task: generate
      - ./run.sh
      - task: extract

  generate:
    desc: 'lsmt - generate sequence'
    dir: '{{.APP}}'
    cmds:
      - echo "#!/bin/bash" > run.sh
      - echo "rm results/*" >> run.sh
      - ~/work/devhands.io/lsmt/lsmt --generate --out="~/work/devhands.io/wrk -c{{.CONNECTIONS}} -t{{.THREADS}} -R{{.R_MASK}} -d{{.DURATION}} -L {{.URL}} > results/wrk_c{{.CONNECTIONS}}_t{{.THREADS}}_R{{.R_MASK}}.txt" --cycles="R={{.SEQ}}" -sleep=20 >> {{.APP}}/run.sh
      - cat run.sh
      - chmod +x run.sh

  clean:
    desc: 'lsmt - clean files'
    dir: '{{.APP}}'
    cmds:
      - rm results/wrk_c{{.CONNECTIONS}}_t{{.THREADS}}_R*.txt

  extract:
    desc: 'lsmt - extract results'
    dir: '{{.APP}}'
    cmds:
      - ~/work/devhands.io/lsmt/lsmt --extract --origin=wrk --files="results/wrk_c{{.CONNECTIONS}}_t{{.THREADS}}_R*.txt" --out="{ Test:\"get-1\", R:{{"{{R}}"}}, rps:{{"{{rps}}"}}, l:{{"{{latency_p99}}"}} }," | sort -t ',' -n -k2.4
