version: '3.1'

services:
  appdb:
    image: postgres:16.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demodb
      POSTGRES_USER: demo
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data/
  redis:
    image: redis:7.0.11
    ports:
      - "6379:6379"